### ISSUE TITLE
Screenshots in der Readme

### ISSUE THREAD

**Issue by staabm** [dtpop/redaktionsassistent#1]

**Comment by dtpop** [comment]
Ich hab das schon probiert. Kriege es aber nicht hin :-(

![bildschirm_redaktionsassistent_fuer_redaxo](https://user-images.githubusercontent.com/1282121/56864370-ebf7c900-69c1-11e9-9df3-a2d3d5884d51.jpg)

Deswegen hier mal ein Ersatzscreenshot.

Danke für den Hinweis!

**Comment by dtpop** [comment]
Habs hingekriegt.
