### ISSUE TITLE
Import-Funktion für bestehende Artikel

### ISSUE THREAD

**Issue by polarpixel** [dtpop/redaktionsassistent#2]
Super wäre eine Option, um bestehende Artikel nachträglich in den Redaktionsassistent zu importieren.

**Comment by dtpop** [comment]
Nach diversen Fehlversuchen verwerfe ich nun die Idee einem bestehenden Datensatz im Redaktionsassistenten einen vorhandenen Artikel zuzuordnen. Es macht einfach zu viele Konflikte. So wäre es theoretisch möglich einen bereits im Redaktionsassistenten zugeordneten Artikel nochmal zuzuordnen. Das müsste verhindert werden. Auch ist die Synchronisation von Werten (Artikelname, art_online_from-Datum) nicht eindeutig möglich bzw. sinnvoll. Soll nun der Artikelname aus dem Artikel oder dem Redaktionsassistenten verwendet werden?

**Comment by dtpop** [comment]
Als separate Zuordnungsseite eingebaut.
